### ISSUE TITLE
Is there a mistake in your README.md for manjaro-bootsplash-green?

### ISSUE THREAD

**Issue by abrahammurciano** [GrayJack/manjaro-grayjack#1]
Under installation instructions it says to run this

    git clone https://github.com/Blacksuan19/Bootsplash-Themes.git

Did you perhaps put the wrong link? This is a link to another repo, which doesnt contain the folder which the next instruction says to `cd` into.

I imagine I'm to instead download the folder from your git repository, but I thought you might want to know if you did put the wrong link.

**Comment by GrayJack** [comment]
Yes, it is, it started as a fork of that, I'll fix it, thanks

**Comment by GrayJack** [comment]
Should be fixed now. Thanks to spot this error!! :smile:
